# Generated by Django 2.2.2 on 2021-01-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_inauguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inauguration',
        ),
    ]
