language: python
dist: xenial

python:
  - 3.6

env:
  SECRET_KEY: sample_secret_key
  HOST: "*"
  DB_TYPE: 'sqlite3'
  DEBUG: 'True'
  MOCK_SMS_EMAIL: 'True'
  AWS_SECRET_ACCESS_KEY: 'your_aws_secret_access_key'
  AWS_ACCESS_KEY_ID: 'your_aws_access_key_id'

install:
  - pip install -r requirements.txt

before_script:
  - export DJANGO_SETTINGS_MODULE=server.settings
  - export PYTHONPATH=$HOME/builds/ECellNitrr/EcellWeb2k19/
  - export PIP_USE_MIRRORS=true

  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test 
