language: python
dist: xenial

python:
  - 3.6

install:
  - pip install -r requirements.txt

env:
  SECRET_KEY: sameple_secret_key
  ALLOWED_HOSTS: "*"
  DEBUG: 'True'
  MOCK_EMAIL: 'True'
  DB_TYPE='sqlite3'
 
before_script:
  - export DJANGO_SETTINGS_MODULE=server.settings
  - export PYTHONPATH=$HOME/builds/ECellNitrr/EcellWeb2k19/
  - export PIP_USE_MIRRORS=true

  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test 
