# Generated by Django 3.0.5 on 2022-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_auto_20190830_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='importance',
            field=models.FloatField(default=0),
        ),
    ]
