# Generated by Django 3.0.5 on 2022-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_auto_20221120_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='spons_type',
            field=models.CharField(choices=[['TLS', 'Title'], ['ATS', 'Associate'], ['PLS', 'Platinum'], ['GDS', 'Gold'], ['SLS', 'Silver'], ['BRS', 'Bronze'], ['PRS', 'Partner']], default='ATS', max_length=3),
        ),
    ]
