name: Docker Compose Actions Workflow
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v2
      - name: Build the stack on localhost
        run: docker-compose up
      
